### ISSUE TITLE
The dice roller API returns 0 in all cases

### ISSUE THREAD

**Issue by tdba** [tdba/dice-roller#1]

**Comment by will-fr** [comment]
Works as designed 👍 

// chosen by fair dice roll
// guaranteed to be random. 

https://xkcd.com/221/

**Comment by tdba** [comment]
> Works as designed 👍
> 
> // chosen by fair dice roll
> // guaranteed to be random.
> 
> https://xkcd.com/221/

@will-fr 
0 Is not included in the sides of a D6 ;) 
But we probably rolled one for 2020, it was beyond critical 1
